config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :questions

  resources :advertisements

  post 'users/confirm' => 'users#confirm'

  root 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :sponsored_posts, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, length: {minimum: 5}, presence: true
  validates :description, length: {minimum: 15}, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show, :new, :create]


  def index
    @topics= Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Dish was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "Error saving dish. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the dish."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def authorize_user
    unless current_user.admin? || current_user.moderator?
      flash[:alert] = "You must be an admin or moderator to do that."
      redirect_to topics_path
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/views/topics/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for dishes:</p>
    <ul>
      <li>Make sure the dish isn't a duplicate.</li>
      <li>Keep grandma's name out of the Dish, save that for the recipes!</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
        <% if topic.errors.any? %>
            <div class="alert alert-danger">
              <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
              <ul>
                <% topic.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <%= form_group_tag(topic.errors[:name]) do %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', placeholder: "Enter dish name" %>
        <% end %>
        <%= form_group_tag(topic.errors[:description]) do %>
            <%= f.label :description %>
            <%= f.text_area :description, rows: 4, class: 'form-control', placeholder: "Enter dish description. What country is it from? What are the traditional ingredients? Techniques?" %>
            <div class="form-group">
              <%= f.label :public, class: 'checkbox' do %>
                  <%= f.check_box :public %> Public dish
              <% end %>
            </div>
            <%= f.submit "Save", class: 'btn btn-success' %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/topics/_topic.html.erb
<% @topics.each do |topic| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to topic.name, topic %>
        </h4>
        <small>
          <%= topic.description %>
        </small>
      </div>
    </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Dish</h1>

<%= render partial: 'form', locals: { topic: @topic } %>

app/views/topics/index.html.erb
<h1>Dishes</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: 'topic', locals: { topic: @topic } %>
  </div>
  <% if current_user %>
    <div class="col-md-4">
        <%= link_to "New Dish", new_topic_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Dish</h1>

<%= render partial: 'form', locals: { topic: @topic } %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
<% if user_is_authorized_for_topics? %>
  <%= link_to "Edit Dish", edit_topic_path, class: 'btn btn-success' %>
  <%= link_to "Delete Dish", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
    <% @topic.posts.each do |post| %>
        <div class="media">
          <%= render partial: 'votes/voter', locals: { post: post } %>
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to post.title, topic_post_path(@topic, post) %>
            </h4>
            <small>
              submitted <%= time_ago_in_words(post.created_at) %> ago <br>
              <%= post.comments.count %> Comments
            </small>
          </div>
        </div>
    <% end %>
  </div>
  <% if current_user %>
    <div class="col-md-4">
        <%= link_to "New Recipe", new_topic_post_path(@topic), class: 'btn btn-success' %>
    </div>
  <% end %>
</div>