config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :questions

  resources :advertisements

  post 'users/confirm' => 'users#confirm'

  root 'welcome#index'

end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/controllers/sponsored_posts_controller.rb
class SponsoredPostsController < ApplicationController
  def show
    @sponsored_post = SponsoredPost.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @sponsored_post = SponsoredPost.new
  end

  def create
    @sponsored_post = SponsoredPost.new
    @sponsored_post.title = params[:sponsored_post][:title]
    @sponsored_post.body = params[:sponsored_post][:body]
    @sponsored_post.price = 15
    @topic = Topic.find(params[:topic_id])
    @sponsored_post.topic = @topic

    if @sponsored_post.save
      flash[:notice] = "Sponsored Post was saved."
      redirect_to [@topic, @sponsored_post]
    else
      flash.now[:alert] = "There was an error saving the sponsored post. Please try again."
      render :new
    end
  end

  def edit
    @sponsored_post = SponsoredPost.find(params[:id])
  end

  def update
    @sponsored_post = SponsoredPost.find(params[:id])
    @sponsored_post.title = params[:sponsored_post][:title]
    @sponsored_post.body = params[:sponsored_post][:body]

    if @sponsored_post.save
      flash[:notice] = "Post was updated."
      redirect_to [@sponsored_post.topic, @sponsored_post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @sponsored_post = SponsoredPost.find(params[:id])

    if @sponsored_post.destroy
      flash[:notice] = "\"#{@sponsored_post.title}\" was deleted successfully."
      redirect_to @sponsored_post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end
end

app/helpers/sponsored_posts_helper.rb
module SponsoredPostsHelper
end

app/views/sponsored_posts/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for sponsored posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [topic, sponsored_post] do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, overflow: 'scroll', class: 'form-control', placeholder: "Enter post body" %>
        </div>
        <div class="form-group">
          <p>Price: $15</p>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
    <% end %>
  </div>
</div>

app/views/sponsored_posts/edit.html.erb
<h1>New Sponsored Post</h1>

<%= render partial: 'form', locals: { topic: @sponsored_post.topic, sponsored_post: @sponsored_post } %>

app/views/sponsored_posts/new.html.erb
<h1>New Sponsored Post</h1>

<%= render partial: 'form', locals: { topic: @topic, sponsored_post: @sponsored_post } %>

app/views/sponsored_posts/show.html.erb
<h1><%= @sponsored_post.title %> -- Sponsored Post</h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @sponsored_post.body %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_topic_sponsored_post_path(@sponsored_post.topic, @sponsored_post), class: 'btn btn-success' %>
    <%= link_to "Delete Post", [@sponsored_post.topic, @sponsored_post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this sponsored post?' } %>
    <%= link_to "Topic", [@sponsored_post.topic], class: 'btn btn-default' %>
  </div>
</div>